/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AudioPlayer: typeof import('./src/components/AudioPlayer.vue')['default']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSlider: typeof import('element-plus/es')['ElSlider']
  }
}
